version: '3.8'

services:
  ziz-tasks:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ziz_tasks_app
    ports:
      - "127.0.0.1:8870:3001"
    restart: always
    environment:
      - PORT=3001
      - NODE_ENV=production
    volumes:
      - ./server/db.json:/app/server/db.json
