import { Project, Task, User } from '../types/rbac';

export const INITIAL_USERS: User[] = [
  {
    id: 'u_abylai',
    name: 'Абылай Жусипбек',
    email: 'abylai@ziz.kz',
    role: 'admin',
    isActive: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj_crm',
    name: 'Редизайн сайта ziz.kz',
    key: 'ZIZ',
    description: 'Разработка таск-трекера Ziz Tasks и модулей автоматизации продаж.',
    memberIds: ['u_abylai', 'u_aldiyar', 'u_dauren', 'u_zhanibek'],
    deadline: '30 авг',
    color: '#2754FF',
    statusBadge: 'новое сообщение',
    completedTasksCount: 5,
    totalTasksCount: 12,
    spec: {
      currentVersionId: 'ver_v2',
      versions: [
        {
          id: 'ver_v1',
          versionNumber: 1,
          type: 'text',
          title: 'Первоначальное ТЗ CRM',
          content: 'Разработать модуль управления задачами с ролевой моделью (Админ, PM, Разработчик).',
          changelog: 'Базовая редакция ТЗ.',
          createdBy: 'u_aldiyar',
          createdAt: '2026-02-01T10:00:00Z',
        },
        {
          id: 'ver_v2',
          versionNumber: 2,
          type: 'text',
          title: 'ТЗ CRM v2.4 (Дизайн система и ролевая модель)',
          content: 'Добавить строгое логирование действий (кто, что, когда), скрывать неразрешенные UI элементы на фронтенде и валидировать все операции на бэкенде.',
          changelog: 'Уточнены ограничения для Разработчиков и PM.',
          createdBy: 'u_aldiyar',
          createdAt: '2026-02-03T14:30:00Z',
        },
      ],
      questions: [],
    },
    documents: [
      {
        id: 'doc_1',
        projectId: 'proj_crm',
        title: 'Договор на разработку CRM Ziz Tasks №04/2026',
        category: 'contract',
        amount: '2 800 000 ₸',
        fileName: 'contract_ziz_crm_04_2026.pdf',
        fileUrl: '/documents/contract_ziz_crm.pdf',
        status: 'signed',
        uploadedBy: 'Абылай Жусипбек',
        uploadedAt: '2026-01-10T11:00:00Z',
        notes: 'Подписан обоими сторонами. Базовый договор оказания услуг.',
      },
      {
        id: 'doc_2',
        projectId: 'proj_crm',
        title: 'Счёт на оплату №841 (Авансовый платёж 50%)',
        category: 'invoice',
        amount: '1 400 000 ₸',
        fileName: 'invoice_841_advance.pdf',
        fileUrl: '/documents/invoice_841.pdf',
        status: 'paid',
        uploadedBy: 'Алдияр Сакен',
        uploadedAt: '2026-01-12T14:30:00Z',
        notes: 'Оплата прошла 12 января. Подтверждение из банка получено.',
      },
    ],
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-02-04T11:00:00Z',
  },
  {
    id: 'proj_mobile',
    name: 'Мобильное приложение',
    key: 'MOB',
    description: 'iOS и Android приложение для клиентов ZIZ INC.',
    memberIds: ['u_abylai', 'u_aldiyar', 'u_dauren'],
    deadline: '15 окт',
    color: '#1E293B',
    updatedAtText: 'обновлено 2 ч назад',
    completedTasksCount: 5,
    totalTasksCount: 28,
    spec: { currentVersionId: '', versions: [], questions: [] },
    createdAt: '2026-02-02T09:00:00Z',
    updatedAt: '2026-02-05T10:00:00Z',
  },
  {
    id: 'proj_payments',
    name: 'CRM: интеграция оплат',
    key: 'PAY',
    description: 'Интеграция с Kaspi Pay и эквайрингом Halyk Bank.',
    memberIds: ['u_abylai', 'u_aldiyar', 'u_zhanibek'],
    deadline: 'без дедлайна',
    color: '#10B981',
    updatedAtText: 'обновлено вчера',
    completedTasksCount: 5,
    totalTasksCount: 7,
    spec: { currentVersionId: '', versions: [], questions: [] },
    createdAt: '2026-02-03T09:00:00Z',
    updatedAt: '2026-02-04T18:00:00Z',
  },
  {
    id: 'proj_archive_spring',
    name: 'Лендинг акции «Весна»',
    key: 'SPR',
    description: 'Промо-страница весенней промо-акции.',
    memberIds: ['u_abylai', 'u_aldiyar'],
    deadline: 'завершён 12 мая',
    color: '#94A3B8',
    isArchived: true,
    completedTasksCount: 9,
    totalTasksCount: 9,
    spec: { currentVersionId: '', versions: [], questions: [] },
    createdAt: '2026-01-01T09:00:00Z',
    updatedAt: '2026-05-12T18:00:00Z',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task_1',
    projectId: 'proj_crm',
    title: 'Реализовать серверный RBAC маппер',
    description: 'Написать модули проверки прав и вызывать assertCanMoveTask и assertCanManageUsers перед выполнением мутаций.',
    status: 'doing',
    priority: 'high',
    deadline: '2026-08-10',
    assigneeId: 'u_dauren', // Assigned to Dauren
    createdById: 'u_aldiyar',
    checklist: [
      { id: 'c1', title: 'Определить перечень матриц прав', completed: true, completedBy: 'Даурен Бекузаков' },
      { id: 'c2', title: 'Написать проверки вызова ошибок', completed: false },
    ],
    comments: [
      {
        id: 'cm1',
        taskId: 'task_1',
        authorId: 'u_aldiyar',
        authorName: 'Алдияр Сакен',
        content: 'Пожалуйста, убедись, что разработчик может двигать только свои задачи.',
        createdAt: '2026-02-04T10:00:00Z',
      },
    ],
    attachments: [
      {
        id: 'att1',
        taskId: 'task_1',
        fileName: 'rbac_schema.png',
        fileUrl: '/mock/rbac_schema.png',
        fileSize: 102400,
        uploadedBy: 'u_dauren',
        uploadedAt: '2026-02-04T12:00:00Z',
      },
    ],
    createdAt: '2026-02-03T10:00:00Z',
    updatedAt: '2026-02-04T12:00:00Z',
  },
  {
    id: 'task_2',
    projectId: 'proj_crm',
    title: 'Вёрстка макетов авторизации и доски Ziz Tasks',
    description: 'Интегрировать логотип ZIZ INC. и компоненты авторизации и канбан-доски.',
    status: 'doing',
    priority: 'urgent',
    deadline: '2026-08-06',
    assigneeId: 'u_zhanibek', // Assigned to Zhanibek
    createdById: 'u_aldiyar',
    checklist: [
      { id: 'c3', title: 'Проверить мобильную адаптивность и шрифты Gilroy/Montserrat', completed: true, completedBy: 'Жанибек Баянов' },
    ],
    comments: [],
    attachments: [],
    createdAt: '2026-02-03T11:00:00Z',
    updatedAt: '2026-02-03T11:00:00Z',
  },
  {
    id: 'task_3',
    projectId: 'proj_crm',
    title: 'Интеграция API спецификаций и версионирования ТЗ',
    description: 'Реализовать вызов методов выгрузки ТЗ и публикации ответов на вопросы.',
    status: 'todo',
    priority: 'medium',
    deadline: '2026-08-15',
    assigneeId: 'u_dauren',
    createdById: 'u_aldiyar',
    checklist: [],
    comments: [],
    attachments: [],
    createdAt: '2026-02-04T15:00:00Z',
    updatedAt: '2026-02-05T08:00:00Z',
  },
  {
    id: 'task_4',
    projectId: 'proj_crm',
    title: 'Оптимизация производительности рендеринга карточек',
    description: 'Добавить мемоизацию для списка задач в KanbanBoard.',
    status: 'done',
    priority: 'low',
    deadline: '2026-08-02',
    assigneeId: 'u_zhanibek',
    createdById: 'u_aldiyar',
    checklist: [],
    comments: [],
    attachments: [],
    createdAt: '2026-02-01T15:00:00Z',
    updatedAt: '2026-08-02T18:00:00Z',
  },
];
